spring:
  datasource:
      url:  jdbc:mysql://localhost:3306/excel?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 6000
      minEvictableIdleTimeMillis: 300000
mybatis:
  typeAliasesPackage: com.dxc.excel.model
  mapperLocations: classpath:mapper/*.xml